# In this make file we will try to create a target that will run toaster
# Toaster is started using the command source toaster start
# however we also need to source the oe-init-build-env command first
# Can you fill in this make file to run toaster?

INFO_MESSAGE ="" #Fill a message to greet the users.
COMMAND_FOR_TOASTER ="" #Fill the command here


#Targets
run-toaster:
	echo "${INFO_MESSAGE}"
	@echo "${COMMAND_FOR_TOASTER}" #The command to run toaster
