hello:
	echo "This is a simple Makefile"
	echo "This line will print if the file hello does not exist."

blah: blah.*
	gcc -o blah blah.c
	sh blah.sh
	ls
# Easy level -> Get the c file to run
# Intermediate level -> Get the shell script to run 
# Advanced level -> call the cpp file from the shell script.
