# This makefile is used to automate tasks related to yocto project.
# Just run `make <target>` to execute the target.

# For example, to build the image, run `make build-image`.
# To build the toolchain, run `make build-toolchain`.


# Task 1:
# Populate the build-images with an @echo "Saying it is building the image"
# Populate the build-image with and @echo "cd ~/work/poky/poky/build && source oe-init-build-env && bitbake core-image-minimal"


# Task 2:
# Populate the clean-build with an @echo "Saying it is cleaning the build directory"
# Populate the clean-build with and @echo "cd ~/work/poky/poky/build && source oe-init-build-env && bitbake -c cleanall"

# Targets
build-image: #Leave this line empty

# One more target?	





