# Example of defining BBLAYERS with some additional information
BBLAYERS ?= " \
  /home/solna/yocto/poky/meta \
  /home/solna/yocto/poky/meta-poky \
  /home/solna/yocto/poky/meta-yocto-bsp \
"

# Targets
example:
	@echo "This is an example target"

info:
	@echo "BBLAYERS contains:"
	@echo $(BBLAYERS)

