
# Note shell is changed to bash to enable sourcing.
SHELL := /bin/bash

#Tip : Remember to give a tab spacing when you run your commands.
# Task 1:
# Populate a target called build-images with an @echo "Saying it is building the image"
# Populate the build-image with and @echo "cd ~/work/poky/poky/ && source oe-init-build-env && bitbake core-image-minimal"


# Task 2:
# Create a target called clean-build
# Populate the clean-build with an @echo "Saying it is cleaning the build directory"
# Populate the clean-build with and @echo "cd ~/work/poky/poky && source oe-init-build-env && bitbake -c cleanall"
# Remember we don't want to clean our build as it would cause issues with the course!!

# Targets
build-image: #Leave this line empty

# Hint: One more target?	


