
# There is a called "extract"
# Inside this target,  print a message that you will be extracting to the directory created by extract"
# You will also echo the command that will be use which is : devtool update ${RECIPE} ${WORKDIR/dummy_directory}
# named "core-image-minimal" to ${WORKDIR}

# Create a target called clean-extract which would clean the directory created by extract
# 	echo "Removing extracted source from ${WORKDIR}"
#    How will you remove a file?

WORKDIR ?= "~"
RECIPE ?= "hello"

extract:
	mkdir -p ${WORKDIR}/dummy_directory	
# Something is missing here 
# Something is missing here


# In clean_extract we need ot remove the directory created and display a message
clean-extract:


